name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        runs:
          pip install -r requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # add figure to the report
          echo "##Validating results by region"
          cml-publish by_region.png --md >> report.md
          cml-send-comment report